# Generated by Django 5.2.17 on 2026-09-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests", "0003_servicerequest_assigned_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OFFER_RECEIVED", "Nouvelle offre"),
                            ("REQUEST_ACCEPTED", "Demande attribuée"),
                            ("OFFER_CANCELLED", "Offre annulée"),
                            ("PROVIDER_EN_ROUTE", "Prestataire en route"),
                            ("PROVIDER_ARRIVED", "Prestataire arrivé"),
                            ("WORK_STARTED", "Intervention commencée"),
                            ("PROVIDER_COMPLETED", "Intervention terminée"),
                            ("CLIENT_CONFIRMED", "Fin confirmée"),
                            ("REVIEW_RECEIVED", "Avis reçu"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.CharField(max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="requests.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "-created_at"],
                        name="notif_rec_read_created_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("service_request__isnull", False)),
                        fields=("recipient", "service_request", "kind"),
                        name="notifications_unique_request_event",
                    )
                ],
            },
        ),
    ]
