# Generated by Django 5.2.17 on 2026-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('OFFER_RECEIVED', 'Nouvelle offre'), ('REQUEST_UNMATCHED', 'Demande sans prestataire'), ('REQUEST_LOCATION_PENDING', 'Zone à vérifier'), ('REQUEST_ACCEPTED', 'Demande attribuée'), ('OFFER_CANCELLED', 'Offre annulée'), ('PROVIDER_EN_ROUTE', 'Prestataire en route'), ('PROVIDER_ARRIVED', 'Prestataire arrivé'), ('WORK_STARTED', 'Intervention commencée'), ('PROVIDER_COMPLETED', 'Intervention terminée'), ('CLIENT_CONFIRMED', 'Fin confirmée'), ('REVIEW_RECEIVED', 'Avis reçu')], max_length=32),
        ),
    ]
