# Generated by Django 5.2.17 on 2026-09-23 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0002_bamako'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Refusé'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=10)),
                ('is_available', models.BooleanField(default=False)),
                ('identity_checked', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_areas', models.ManyToManyField(related_name='providers', to='locations.neighborhood')),
                ('trades', models.ManyToManyField(related_name='providers', to='catalog.trade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'id'],
                'permissions': [('verify_provider', 'Peut vérifier les prestataires')],
            },
        ),
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé'), ('SUSPENDED', 'Suspendu'), ('REOPENED', 'Réouvert')], max_length=10)),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='providers.providerprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
