# Generated by Django 5.2.17 on 2026-09-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient", models.CharField(max_length=16)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("PHONE_VERIFICATION", "Vérification du téléphone"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("CONSOLE", "Console locale"),
                            ("TWILIO", "Twilio"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Accepté par le fournisseur"),
                            ("FAILED", "Échec"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("request_ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("provider_message_id", models.CharField(blank=True, max_length=64)),
                ("provider_status", models.CharField(blank=True, max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_delivery_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="sms_recipient_created_idx",
                    ),
                ],
            },
        ),
    ]
