# Generated by Django 5.2.17 on 2026-09-23 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0002_bamako'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('address_detail', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normale'), ('URGENT', 'Urgente')], default='NORMAL', max_length=6)),
                ('status', models.CharField(choices=[('CREATED', 'Enregistrée'), ('SEARCHING', 'Recherche en cours'), ('OFFERED', 'Proposée'), ('ACCEPTED', 'Acceptée'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrivé'), ('IN_PROGRESS', 'En cours'), ('PROVIDER_COMPLETED', 'Terminée par le prestataire'), ('CLIENT_CONFIRMED', 'Confirmée par le client'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'Contestée')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='locations.neighborhood')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='catalog.trade')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('CREATED', 'Enregistrée'), ('SEARCHING', 'Recherche en cours'), ('OFFERED', 'Proposée'), ('ACCEPTED', 'Acceptée'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrivé'), ('IN_PROGRESS', 'En cours'), ('PROVIDER_COMPLETED', 'Terminée par le prestataire'), ('CLIENT_CONFIRMED', 'Confirmée par le client'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'Contestée')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='requests.servicerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('new_status', 'CREATED'), ('previous_status', '')), fields=('service_request',), name='requests_one_initial_history')],
            },
        ),
    ]
