# Generated by Django 5.2.17 on 2026-09-23 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('dispatch_request', 'Peut lancer la recherche de prestataires')]},
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('DECLINED', 'Refusée'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='providers.providerprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='requests.servicerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('service_request', 'provider'), name='requests_unique_offer_provider')],
            },
        ),
    ]
