# Generated by Django 5.2.17 on 2026-09-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('requests', '0002_alter_servicerequest_options_serviceoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to='providers.providerprofile'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('service_request',), name='requests_one_accepted_offer'),
        ),
    ]
