# Generated by Django 5.2.17 on 2026-09-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_mali_regions'),
        ('requests', '0003_servicerequest_assigned_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requested_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_commune',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.region'),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='new_status',
            field=models.CharField(choices=[('CREATED', 'Enregistrée'), ('LOCATION_PENDING', 'Zone à vérifier'), ('SEARCHING', 'Recherche en cours'), ('OFFERED', 'Proposée'), ('ACCEPTED', 'Acceptée'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrivé'), ('IN_PROGRESS', 'En cours'), ('PROVIDER_COMPLETED', 'Terminée par le prestataire'), ('CLIENT_CONFIRMED', 'Confirmée par le client'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'Contestée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='locations.neighborhood'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Enregistrée'), ('LOCATION_PENDING', 'Zone à vérifier'), ('SEARCHING', 'Recherche en cours'), ('OFFERED', 'Proposée'), ('ACCEPTED', 'Acceptée'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrivé'), ('IN_PROGRESS', 'En cours'), ('PROVIDER_COMPLETED', 'Terminée par le prestataire'), ('CLIENT_CONFIRMED', 'Confirmée par le client'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'Contestée')], default='CREATED', max_length=20),
        ),
    ]
