# Generated by Django 5.2.17 on 2026-09-28 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_servicerequest_requested_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requeststatushistory',
            name='requests_one_initial_history',
        ),
        migrations.AddConstraint(
            model_name='requeststatushistory',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_status', '')), fields=('service_request',), name='requests_one_initial_history'),
        ),
    ]
