# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='locations_city_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='locations.city')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='locations.commune')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('city'), name='locations_commune_city_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('commune'), name='locations_neighborhood_commune_name_ci_unique'),
        ),
    ]
