# Generated by Django 5.2.17 on 2026-09-24

import apps.payments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ACTIVATE", "Activation"),
                            ("RENEW", "Renouvellement"),
                        ],
                        max_length=10,
                    ),
                ),
                ("payment_provider", models.CharField(max_length=50)),
                (
                    "merchant_reference",
                    models.CharField(
                        default=apps.payments.models.generate_merchant_reference,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64)),
                ("amount_xof", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("plan_code_snapshot", models.CharField(max_length=50)),
                ("plan_name_snapshot", models.CharField(max_length=120)),
                ("duration_days_snapshot", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCEEDED", "Réussi"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fulfillment_error_code",
                    models.CharField(blank=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="subscriptions.providersubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("manage_payments", "Peut consulter et gérer les paiements"),
                ],
                "indexes": [
                    models.Index(
                        fields=["provider", "status", "-created_at"],
                        name="payments_provider_status_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "idempotency_key"),
                        name="payments_unique_provider_idempotency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "XOF")),
                        name="payments_currency_xof_only",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_fingerprint",
                    models.CharField(max_length=64, unique=True),
                ),
                ("reported_status", models.CharField(max_length=12)),
                (
                    "provider_transaction_id",
                    models.CharField(max_length=128),
                ),
                ("amount_xof", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("accepted", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["received_at", "id"],
            },
        ),
    ]
