# Generated by Django 5.2.17 on 2026-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
