# Generated by Django 5.2.17 on 2026-09-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests", "0003_servicerequest_assigned_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SERVICE_QUALITY", "Qualité du service"),
                            ("BEHAVIOR", "Comportement"),
                            ("PAYMENT", "Paiement"),
                            ("SAFETY", "Sécurité"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouverte"),
                            ("UNDER_REVIEW", "En cours d'examen"),
                            ("RESOLVED", "Résolue"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "previous_request_status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Enregistrée"),
                            ("SEARCHING", "Recherche en cours"),
                            ("OFFERED", "Proposée"),
                            ("ACCEPTED", "Acceptée"),
                            ("EN_ROUTE", "En route"),
                            ("ARRIVED", "Arrivé"),
                            ("IN_PROGRESS", "En cours"),
                            ("PROVIDER_COMPLETED", "Terminée par le prestataire"),
                            ("CLIENT_CONFIRMED", "Confirmée par le client"),
                            ("CANCELLED", "Annulée"),
                            ("DISPUTED", "Contestée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.CharField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="requests.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="complaints_status_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["OPEN", "UNDER_REVIEW"])),
                        fields=("service_request",),
                        name="complaints_one_active_per_request",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplaintStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouverte"),
                            ("UNDER_REVIEW", "En cours d'examen"),
                            ("RESOLVED", "Résolue"),
                            ("REJECTED", "Rejetée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaint_status_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
