# Generated by Django 5.2.17 on 2026-09-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='previous_request_status',
            field=models.CharField(choices=[('CREATED', 'Enregistrée'), ('LOCATION_PENDING', 'Zone à vérifier'), ('SEARCHING', 'Recherche en cours'), ('OFFERED', 'Proposée'), ('ACCEPTED', 'Acceptée'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrivé'), ('IN_PROGRESS', 'En cours'), ('PROVIDER_COMPLETED', 'Terminée par le prestataire'), ('CLIENT_CONFIRMED', 'Confirmée par le client'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'Contestée')], max_length=20),
        ),
    ]
